# Generated by Django 5.1.6 on 2025-03-08 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libraryadmin',
            name='working_hours',
        ),
        migrations.AlterField(
            model_name='author',
            name='alive_or_dead',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='page',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='record',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.libraryadmin'),
        ),
        migrations.AlterField(
            model_name='record',
            name='date_received',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='book_quantity',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
